name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  build:
    runs-on: [self-hosted]
    needs: lint
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
